meta_product_name: "AnimePanda"
meta_title: "AnimePanda - Your own AI anime curator. Find your next favorite anime now!"
meta_description: "I am the AnimePanda and I will recoommend animes for you!"
meta_image: "Anime_Panda_banner.png"
